name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'e2e-test-project'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['data']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target' # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_packages'

vars:
  project_name: '`singular-vector-135519`'
  table_1: 'test_table1'
  table_2: 'users'
