name: 'dbt_postgres_test'
version: '1.0.0'
config-version: 2

profile: 'e2e-test-project-postgres'

model-paths: ['models']
seed-paths: ['data']
analysis-paths: ['analysis']
test-paths: ['tests']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  dbt_postgres_test:
    +materialized: table
