SELECT 
    CAST(1234567 AS VARCHAR),
    CAST(1234567 AS VARCHAR(7)),
    CAST(1 AS NVARCHAR2),
    CAST(1 AS CHARACTER VARYING),
    CAST(1 AS CHARACTER VARYING(7)),
    CAST(1 AS CHAR VARYING),
    CAST(1 AS NCHAR VARYING),
