SELECT
    IS_DATE_VALUE(TRUE),
    IS_DATE_VALUE(TO_VARIANT('Sample text')),
    IS_DATE_VALUE(1),
    IS_DATE_VALUE(TO_VARIANT(TO_DATE('2023-04-20', 'YYYY-MM-DD'))),
    IS_DATE_VALUE(TO_NUMBER(1)),
    IS_DATE_VALUE(array_construct())
