WITH ORDERS AS (
    SELECT 1 AS O_ORDERKEY, 1000 AS O_TOTALPRICE UNION ALL
    SELECT 2 AS O_ORDERKEY, 2000 AS O_TOTALPRICE UNION ALL
    SELECT 3 AS O_ORDERKEY, 3000 AS O_TOTALPRICE UNION ALL
    SELECT 4 AS O_ORDERKEY, 4000 AS O_TOTALPRICE UNION ALL
    SELECT 5 AS O_ORDERKEY, 5000 AS O_TOTALPRICE UNION ALL
    SELECT 6 AS O_ORDERKEY, 6000 AS O_TOTALPRICE UNION ALL
    SELECT 7 AS O_ORDERKEY, 7000 AS O_TOTALPRICE UNION ALL
    SELECT 8 AS O_ORDERKEY, 8000 AS O_TOTALPRICE UNION ALL
    SELECT 9 AS O_ORDERKEY, 9000 AS O_TOTALPRICE UNION ALL
    SELECT 10 AS O_ORDERKEY, 10000 AS O_TOTALPRICE
),
cte1 AS (
    SELECT MINHASH(100, O_TOTALPRICE) mh FROM ORDERS WHERE O_ORDERKEY <= 5
)
SELECT APPROXIMATE_JACCARD_INDEX((SELECT mh FROM cte1)) AS jaccard_index;
