name: CI

on:
  push:
    branches:
    tags:

jobs:
  test-and-package:
    runs-on: macos-latest
    
    outputs:
      vsix_name: ${{ steps.vars.outputs.vsix_name }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: build and test
        run: |
          npm install
          npm run compile
          npm run lint
          npm run test

      - name: package to vsix file
        run: npx vsce package -o dbt-language-server.vsix --baseImagesUrl=https://storage.googleapis.com/dbt-ls-images

      - name: save vsix name with sha
        id: vars
        run: echo "::set-output name=vsix_name::dbt-language-server-commit-sha-${GITHUB_SHA::7}.vsix"

      - name: create cache
        uses: actions/cache@v2
        with:
          path: |
            ./e2e
            ./dbt-language-server.vsix
          key: ${{ runner.os }}-cache-${{ github.sha }}-${{ github.ref }}

  run-e2e-tests:
    needs: test-and-package

    strategy:
      matrix:
        dbt-version: ['dbt==0.19.1', 'dbt']

    runs-on: macos-latest
    steps:
      - name: load e2e tests and vsix from cache
        uses: actions/cache@v2
        with:
          path: |
            ./e2e
            ./dbt-language-server.vsix
          key: ${{ runner.os }}-cache-${{ github.sha }}-${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'

      - name: prepare profile config
        run: |
          mkdir -p ~/.dbt/
          echo "$BQ_SERVICE_ACCOUNT" > ~/.dbt/bq-test-project.json

          user=$(whoami)
          path=$(eval echo "~${user}")/.dbt/bq-test-project.json

          cat <<EOT > ~/.dbt/profiles.yml

          e2e-test-project:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: singular-vector-135519
                keyfile: ${path}
                dataset: transforms_dbt_default
                threads: 4

          EOT
        env:
          BQ_SERVICE_ACCOUNT: ${{ secrets.BQ_SERVICE_ACCOUNT }}
      - run: pip install ${{ matrix.dbt-version }}
      - run: dbt --version

      - run: unzip dbt-language-server.vsix -d e2e-tests
      - run: node e2e/out/runTest $(pwd)/e2e-tests/extension

      - name: show test logs
        if: always()
        run: |
          ls
          cat e2e/test-fixture/logs/ModelCompiler.txt

  publish:
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }} # main branch or have any tag started with 'v'
    needs: [test-and-package, run-e2e-tests]

    runs-on: macos-latest
    steps:
      - name: load vsix from cache
        uses: actions/cache@v2
        with:
          path: |
            ./e2e
            ./dbt-language-server.vsix
          key: ${{ runner.os }}-cache-${{ github.sha }}-${{ github.ref }}

      - name: prepare vsix for push to GCS
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          VSIX_NAME: ${{ needs.test-and-package.outputs.vsix_name }}
        run: cp dbt-language-server.vsix ${VSIX_NAME}

      - name: push main to GCS
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ needs.test-and-package.outputs.vsix_name }}
          destination: dbt-language-server
          credentials: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      - name: set up node 14.x
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: publish tagged (latest) extension
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: npx vsce publish -i dbt-language-server.vsix -p ${VSCE_TOKEN}
