name: ReleaseToChangelog
on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: update changelog
        run: npx github-release-notes changelog --override --token=$TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update CHANGELOG.md
          delete-branch: true
          title: Update CHANGELOG.md
          reviewers: pgrivachev

