name: ReleaseToChangelog
on:
  release:
    types: [published, edited]
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: generate markdown changelog
        id: changelog
        uses: LSVH/gha-releases-to-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title-template: '# %%TITLE%%'

      - name: print changelog
        run: |
          cat >CHANGELOG.md <<EOF
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: config git
        run: |
          git config user.name "changelog-bot"
          git config user.email "<>"

      - name: update changelog in main
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push origin main
