name: ReleaseToChangelog
on:
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: update changelog
        run: npx github-release-notes changelog --override --token=$TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update CHANGELOG.md [skip ci]
          delete-branch: true
          title: Update CHANGELOG.md [skip ci]
          reviewers: pgrivachev
